refactored SearchAutoComplete function, added TextField props availability
mayyamark/react-components pull request #1
Opened 2023-01-09 16:16 UTC by psimaron

Fixed names, fixed types, refactored SearchAutoComplete function, added TextField props availability, made a callback available to the parent component for the selected option

2023-01-10 08:43 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
>              ...option.InputProps,
тук пропускаме нещо

2023-01-10 08:55 UTC, mayyamark requested changes
отново напомням за къмитите - всяко малко нещо трябва да е в отделен къмит. когато ги правим огромни, нямаме възможност да върнем назад някоя малка промяна, трябва да започнем отначало

2023-01-10 08:55 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
>              ...option.InputProps,
тук пропускаме нещо

2023-01-10 08:55 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
> +  selectedOption: (value: unknown) => void;
`selectedOption` не е подходящо име за callback функция. по-скоро звучи като променлива, в която съхраняваме избраната опция

2023-01-10 08:55 UTC, mayyamark commented on package.json
> +    "@material-ui/core": "^4.12.4",
mui 4? нямаме нужда от него, използваме версия 5

2023-01-10 08:55 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
>        }}
имаме 1 големичък проблем - при селектиране на опция, се изпраща нова заявка

2023-01-10 08:55 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
>    };
тук говорихме да го направим така, че да се подават отвън. обикновено, когато се правят компоненти, то се очаква, че ще се използват от различни проекти, а различните проекти на 100% генерират свои key-ове (финансови причини)

2023-01-10 13:28 UTC, mayyamark requested changes
много добре! последни 2 коментара 👍

2023-01-10 13:28 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
> +      onChange={(event, value) => onCarSelection(value)}
правилно е написано, но името отново не е подходящо - методът се извиква в различни ситуации - при селектиране, при изчистване на полето и т.н.:
<img width="855" alt="Screenshot 2023-01-10 at 15 24 39" src="https://user-images.githubusercontent.com/76959453/211563324-4cab9f5e-5c27-4982-a662-a1b8826c2a10.png">

подходящото име би било `onChangeCallback` - това би подсказало точно какъв е този метод и кога се извиква - callback,  който се изпълнява в `onChange`

2023-01-10 13:28 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
> +  header: HeadersInit;
подаваме повече от 1 header => `headers`

2023-01-10 13:29 UTC, mayyamark commented on src/components/CarAutocomplete/index.tsx
> +      onChange={(event, value) => onCarSelection(value)}
също така, направи го optional този prop, понякога може да няма логика, която да искаме да изпълняваме

2023-01-10 14:46 UTC, mayyamark commented
последно промени името на PR-а - просто Refactor CarAutocomplete да бъде и напиши подробно описание като списък какво е направено. и пак за къмитите!

2023-01-10 15:58 UTC, psimaron commented
> последно промени името на PR-а - просто Refactor CarAutocomplete да бъде и напиши подробно описание като списък какво е направено. и пак за къмитите!

Реших, че е достатъчно малко едното, за да не е в собствен къмът ама добре, разбрах

2023-01-11 08:33 UTC, mayyamark approved these changes
браво, цъкни Squash & merge

2023-01-12 08:34 UTC, merged